-   id: graphql-schema-linter
    name: GraphQL Schema Linter
    description: This hook links GraphQL SDL files.
    entry: npx graphql-schema-linter
    language: node
    files: '\w+\.graphql$'

-   id: format-graphql
    name: Format GraphQL
    description: This hook formats GraphQL schemas
    entry: npx format-graphql --write=true
    language: node
    files: '\w+\.graphql$'

-   id: generate-graphidocs
    name: Generate static site documentation
    description: Runs using @graphidocs/docs from npmjs
    entry: npx graphidocs -s ./schema.graphql --force -o ./doc/schema
    language: node
    files: '\w+\.graphql$'
